language: ruby
cache:
  - directories:
    - /home/travis/.rvm/
sudo: true # need this for libgirepository1.0-dev
addons:
  apt:
    packages:
      - libgirepository1.0-dev # for gobject-introspection
rvm:
  - 2.4.2
  - 2.5.3
  - 2.6.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
